---
- hosts: frontend
  gather_facts: no

  tasks:
    - name: Create the sites-available directory
      become: yes
      file:
        path: /etc/nginx/sites-available
        state: directory

    - name: Copy the site config
      become: yes
      template:
        src: "config/site"
        dest: /etc/nginx/sites-available/testnet.hydranet.ai

    - name: Create the sites-enabled directory
      become: yes
      file:
        path: /etc/nginx/sites-enabled
        state: directory

    - name: Enable the site
      become: yes
      file:
        src: /etc/nginx/sites-available/testnet.hydranet.ai
        dest: /etc/nginx/sites-enabled/testnet.hydranet.ai
        state: link

    # Get SSL certificate
    # Source: https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx
    - name: Install certbot
      become: yes
      snap:
        name: certbot
        classic: yes

    - name: Get SSL certificate
      become: yes
      shell: certbot -n --agree-tos --nginx -m "certbot@wiringbits.net" --domains "testnet.hydranet.ai"
